//! Struct support for staged computations.
//!
//! Field access is built from just three operations, all of which compute the
//! same `base + OFFSET` address (or load from it):
//!
//! - [`LoadField`] (`.get`) — load a `Copy` field's value.
//! - [`FieldAddr`] (`.get_ref`) — a reference to a field, *flavor-preserving*
//!   via [`FieldRefOf`]: a field of a `&T` comes back as `&field`, a field of a
//!   `&mut T` comes back as `&mut field`. The mutability lives entirely in the
//!   associated [`FieldRefOf::Ref`], exactly like `SliceType::ElemRef` in
//!   [`crate::slice`].
//! - [`FieldPath`] (`.field`) — navigate into a nested field of a *by-value*
//!   struct, yielding a raw pointer (`SPtr`) because there is no input lifetime
//!   to borrow from.
//!
//! Field descriptors (the [`Field`] trait) are generated by the derive macro.

use crate::refer::{store_ref, SMutPtr, SPtr, SRef, SRefMut, StoreRef};
use crate::staged::{CompilationContext, IntoStaged, Staged, Var, VarUse};
use crate::types::{CopyType, StagedType};
use cranelift_codegen::ir::{types, InstBuilder, MemFlags};
use std::marker::PhantomData;

// =============================================================================
// Field Trait
// =============================================================================

/// Trait for struct field descriptors.
///
/// This trait is implemented by the proc macro for each field of a struct.
/// It provides type-level information about the field's parent struct,
/// output type, and memory offset.
///
/// # Safety
///
/// `Parent`, `Out`, and `OFFSET` must identify a real `Out` field within the
/// staged runtime representation of `Parent`. `OFFSET` must satisfy the field's
/// alignment and bounds requirements. Prefer descriptors emitted by
/// `#[derive(StagedType)]`.
///
/// ```compile_fail
/// use rust_lms::prelude::*;
///
/// #[derive(Clone, Copy)]
/// struct FabricatedField;
///
/// impl Field for FabricatedField {
///     type Parent = i64;
///     type Out = i64;
///     const OFFSET: usize = 0;
///     const INDEX: usize = 0;
/// }
/// ```
pub unsafe trait Field: Copy {
    /// The parent struct type
    type Parent: StagedType;

    /// The field's type
    type Out: StagedType;

    /// Byte offset of this field from the struct base
    const OFFSET: usize;

    /// Field index (for debugging)
    const INDEX: usize;
}

/// Compile-time witness that two generated field descriptors cannot overlap.
///
/// `#[derive(StagedType)]` implements this trait for every ordered pair of
/// distinct fields. It intentionally does not implement it for a field paired
/// with itself.
///
/// # Safety
///
/// `Self` and `Other` must identify non-overlapping fields of the same parent
/// runtime value.
pub unsafe trait DisjointField<Other>: Field
where
    Other: Field<Parent = Self::Parent>,
{
}

// =============================================================================
// PointerLike: map a pointer-to-parent into a pointer-to-field
// =============================================================================

mod pointer_like_sealed {
    pub trait Sealed {}
}

/// A staged pointer/reference to a parent struct, for field access.
///
/// Carries only the [`Pointee`](Self::Pointee) (the parent struct type), used
/// to constrain a [`Field`]'s `Parent`. The field-reference type itself comes
/// from [`FieldRefOf`]. This trait is sealed because pointer flavor and pointee
/// representation are trusted by field-address lowering.
///
/// ```compile_fail
/// use rust_lms::prelude::*;
///
/// #[repr(C)]
/// #[derive(Clone, Copy, StagedType)]
/// struct FabricatedPointer {
///     raw: u64,
/// }
///
/// impl PointerLike for FabricatedPointer {
///     type Pointee = i64;
/// }
/// ```
pub trait PointerLike: StagedType + pointer_like_sealed::Sealed {
    /// The type this pointer points at (the parent struct, for field access).
    type Pointee: StagedType;
}

impl<'a, P: StagedType> PointerLike for SRef<'a, P> {
    type Pointee = P;
}

impl<'a, P: StagedType> pointer_like_sealed::Sealed for SRef<'a, P> {}

impl<'a, P: StagedType> PointerLike for SRefMut<'a, P> {
    type Pointee = P;
}

impl<'a, P: StagedType> pointer_like_sealed::Sealed for SRefMut<'a, P> {}

// Raw-pointer flavors — so field access works on *baked* pointers
// (`const_ptr`/`const_mut_ptr`), not just Rust references. A field of a `*const T`
// is a `*const field`; of a `*mut T`, a `*mut field`.
impl<P: StagedType> PointerLike for SPtr<P> {
    type Pointee = P;
}

impl<P: StagedType> pointer_like_sealed::Sealed for SPtr<P> {}

impl<P: StagedType> PointerLike for SMutPtr<P> {
    type Pointee = P;
}

impl<P: StagedType> pointer_like_sealed::Sealed for SMutPtr<P> {}

mod reference_like_sealed {
    pub trait Sealed {}
}

/// A staged Rust-reference marker accepted by safe field loads.
///
/// Unlike [`PointerLike`], this sealed trait deliberately excludes raw
/// pointers; raw field loads must use `load_field_unchecked`.
pub trait ReferenceLike: PointerLike + reference_like_sealed::Sealed {}

impl<'a, P: StagedType> reference_like_sealed::Sealed for SRef<'a, P> {}
impl<'a, P: StagedType> ReferenceLike for SRef<'a, P> {}
impl<'a, P: StagedType> reference_like_sealed::Sealed for SRefMut<'a, P> {}
impl<'a, P: StagedType> ReferenceLike for SRefMut<'a, P> {}

/// Maps a parent pointer onto a pointer-to-field of the *same flavor*.
///
/// This is the field-access analogue of [`crate::slice::SliceType`]: a single
/// field-address op ([`FieldAddr`]) serves immutable and mutable references
/// because the result type is encoded here. A field `Out` of a `&T` becomes
/// `SRef<'a, Out>`; of a `&mut T`, `SRefMut<'a, Out>`. The `Out: 'a` bound
/// (expressible because `'a` is in scope on the impl) is what a plain GAT
/// could not state.
pub trait FieldRefOf<Out: StagedType>: PointerLike {
    /// The reference to a field of type `Out`, in this pointer's flavor.
    type Ref: StagedType;
}

impl<'a, P: StagedType, Out: StagedType + 'a> FieldRefOf<Out> for SRef<'a, P> {
    type Ref = SRef<'a, Out>;
}

impl<'a, P: StagedType, Out: StagedType + 'a> FieldRefOf<Out> for SRefMut<'a, P> {
    type Ref = SRefMut<'a, Out>;
}

impl<P: StagedType, Out: StagedType> FieldRefOf<Out> for SPtr<P> {
    type Ref = SPtr<Out>;
}

impl<P: StagedType, Out: StagedType> FieldRefOf<Out> for SMutPtr<P> {
    type Ref = SMutPtr<Out>;
}

// =============================================================================
// LoadField: load a Copy field's value
// =============================================================================

/// Load a field's value from a struct.
///
/// This operation is only valid for `Copy` fields. It computes the field
/// pointer (`base + OFFSET`) and loads the value from memory.
///
/// # Example
/// ```ignore
/// let pt: Var<Point> = ...;
/// let x = pt.get(PointType::x);  // Uses LoadField internally
/// ```
pub struct LoadField<P, F> {
    ptr: P,
    _field: PhantomData<F>,
}

impl<P: Clone, F> Clone for LoadField<P, F> {
    fn clone(&self) -> Self {
        Self {
            ptr: self.ptr.clone(),
            _field: PhantomData,
        }
    }
}

impl<P: Copy, F> Copy for LoadField<P, F> {}

unsafe impl<P, F> Staged for LoadField<P, F>
where
    P: Staged,
    P::Out: StagedType,
    F: Field,
    F::Out: CopyType,
{
    type Out = F::Out;

    fn codegen(&self, ctx: &mut CompilationContext) -> cranelift_codegen::ir::Value {
        let base_ptr = self.ptr.codegen(ctx);
        let offset = F::OFFSET as i32;
        if F::Out::is_copy_struct() {
            let offset = ctx.builder.ins().iconst(types::I64, F::OFFSET as i64);
            ctx.builder.ins().iadd(base_ptr, offset)
        } else {
            ctx.builder.ins().load(
                F::Out::cranelift_type(),
                MemFlags::trusted(),
                base_ptr,
                offset,
            )
        }
    }
}

/// Create an unchecked [`LoadField`] operation.
///
/// Prefer [`CopyFieldAccess::get`], which statically relates the field's parent
/// to the base expression. This escape hatch is for raw pointers and generic
/// expression wrappers whose invariant is established elsewhere.
///
/// # Safety
///
/// At execution, `ptr` must evaluate to a live, aligned base value for
/// `F::Parent`; `F` must describe a field within that value. Raw-pointer bases
/// must additionally be dereferenceable for `F::Out` at `F::OFFSET`.
pub unsafe fn load_field_unchecked<P, F>(ptr: P, _field: F) -> LoadField<P, F>
where
    P: Staged,
    F: Field,
    F::Out: CopyType,
{
    LoadField {
        ptr,
        _field: PhantomData,
    }
}

// =============================================================================
// FieldAddr: reference to a field, flavor-preserving via PointerLike
// =============================================================================

/// A reference to a struct field, computed as `base + OFFSET`.
///
/// The reference flavor follows the parent: addressing a field of a `&T`
/// produces `SRef<'a, F>`, of a `&mut T` produces `SRefMut<'a, F>` — and the
/// input lifetime flows through, so the result can be returned. This single op
/// replaces the former `FieldRef`/`FieldMutRef`/`FieldPtr`/`FieldMutPtr`
/// quartet (they all emitted identical address arithmetic).
pub struct FieldAddr<S, F> {
    base: S,
    _field: PhantomData<F>,
}

impl<S: Clone, F> Clone for FieldAddr<S, F> {
    fn clone(&self) -> Self {
        FieldAddr {
            base: self.base.clone(),
            _field: PhantomData,
        }
    }
}

impl<S: Copy, F> Copy for FieldAddr<S, F> {}

unsafe impl<S, F> Staged for FieldAddr<S, F>
where
    S: Staged,
    S::Out: FieldRefOf<F::Out>,
    F: Field<Parent = <S::Out as PointerLike>::Pointee>,
{
    type Out = <S::Out as FieldRefOf<F::Out>>::Ref;

    fn codegen(&self, ctx: &mut CompilationContext) -> cranelift_codegen::ir::Value {
        let base_ptr = self.base.codegen(ctx);
        let offset = ctx.builder.ins().iconst(types::I64, F::OFFSET as i64);
        ctx.builder.ins().iadd(base_ptr, offset)
    }
}

/// Helper to create a [`FieldAddr`] operation.
pub fn field_addr<S, F>(base: S, _field: F) -> FieldAddr<S, F> {
    FieldAddr {
        base,
        _field: PhantomData,
    }
}

/// A scoped mutable field projection.
///
/// The token borrows its parent staged capability and exposes only terminal
/// operations. It cannot yield an independent `SRefMut` that could overlap a
/// later use of the parent.
pub struct MutField<'borrow, 'stage, T, F>
where
    T: StagedType + 'stage,
    F: Field<Parent = T>,
{
    base: &'borrow mut Var<SRefMut<'stage, T>>,
    field: F,
}

impl<'borrow, 'stage, T, F> MutField<'borrow, 'stage, T, F>
where
    T: StagedType + 'stage,
    F: Field<Parent = T>,
    F::Out: 'stage,
{
    pub(crate) fn use_once(&mut self) -> FieldAddr<VarUse<SRefMut<'stage, T>>, F> {
        FieldAddr {
            base: self.base.use_once(),
            _field: PhantomData,
        }
    }

    /// Load this `Copy` field without allowing its mutable reference to escape.
    pub fn load(&mut self) -> LoadField<VarUse<SRefMut<'stage, T>>, F>
    where
        F::Out: CopyType,
    {
        load_field_mut(self.base, self.field)
    }

    /// Store through this field without allowing its mutable reference to
    /// escape.
    pub fn store<V>(
        &mut self,
        value: V,
    ) -> StoreRef<'stage, FieldAddr<VarUse<SRefMut<'stage, T>>, F>, V::Staged>
    where
        V: IntoStaged<F::Out>,
    {
        store_ref(self.use_once(), value.into_staged())
    }
}

/// Borrow one field of a unique staged struct for terminal operations.
///
/// The parent cannot be reborrowed while the field token remains live:
///
/// ```compile_fail
/// use rust_lms::prelude::*;
///
/// #[repr(C)]
/// #[derive(Clone, Copy, StagedType)]
/// struct Pair {
///     left: i64,
///     right: i64,
/// }
///
/// fn overlapping(mut pair: Var<SRefMut<'static, Pair>>) {
///     let mut left = field_mut(&mut pair, PairType::left());
///     let _right = load_field_mut(&mut pair, PairType::right());
///     let _left = left.load();
/// }
/// ```
pub fn field_mut<'borrow, 'stage, T, F>(
    base: &'borrow mut Var<SRefMut<'stage, T>>,
    field: F,
) -> MutField<'borrow, 'stage, T, F>
where
    T: StagedType + 'stage,
    F: Field<Parent = T>,
    F::Out: 'stage,
{
    MutField { base, field }
}

/// Pair of disjoint mutable field projections returned by [`split_fields_mut`].
pub type SplitFieldsMut<'stage, T, Left, Right> = (
    FieldAddr<VarUse<SRefMut<'stage, T>>, Left>,
    FieldAddr<VarUse<SRefMut<'stage, T>>, Right>,
);

/// Consume a unique staged struct reference and split it into two statically
/// disjoint field references.
///
/// The derive macro does not generate a disjointness witness for the same
/// field, so overlapping splits fail at compile time:
///
/// ```compile_fail
/// use rust_lms::prelude::*;
///
/// #[repr(C)]
/// #[derive(Clone, Copy, StagedType)]
/// struct Pair {
///     left: i64,
///     right: i64,
/// }
///
/// fn duplicate_left(pair: Var<SRefMut<'static, Pair>>) {
///     let _ = split_fields_mut(pair, PairType::left(), PairType::left());
/// }
/// ```
pub fn split_fields_mut<'stage, T, Left, Right>(
    base: Var<SRefMut<'stage, T>>,
    _left: Left,
    _right: Right,
) -> SplitFieldsMut<'stage, T, Left, Right>
where
    T: StagedType + 'stage,
    Left: DisjointField<Right, Parent = T>,
    Right: Field<Parent = T>,
    Left::Out: 'stage,
    Right::Out: 'stage,
{
    (
        FieldAddr {
            base: base.use_once(),
            _field: PhantomData,
        },
        FieldAddr {
            base: base.use_once(),
            _field: PhantomData,
        },
    )
}

/// Load a `CopyType` field through a unique staged mutable-reference variable.
pub fn load_field_mut<'a, T, F>(
    base: &mut Var<SRefMut<'a, T>>,
    _field: F,
) -> LoadField<VarUse<SRefMut<'a, T>>, F>
where
    T: StagedType + 'a,
    F: Field<Parent = T>,
    F::Out: CopyType,
{
    LoadField {
        ptr: base.use_once(),
        _field: PhantomData,
    }
}

// =============================================================================
// FieldPath: lifetime-free navigation for by-value structs
// =============================================================================

/// Lifetime-free field path for accessing nested fields of by-value structs.
///
/// Used when the receiver is passed by value (`Var<T>`): there is no input
/// lifetime to borrow, so navigation yields a raw pointer (`SPtr<F::Out>`).
/// `FieldPath` can be chained further with `.field()` or terminated with
/// `.get()` for `Copy` values.
///
/// # Example
/// ```ignore
/// compiler.fun1("sum", |_ctx, outer: Var<Outer>| {
///     outer.field(OuterType::inner).get(InnerType::value)
/// });
/// ```
pub struct FieldPath<P, F> {
    ptr: P,
    _field: PhantomData<F>,
}

impl<P, F> Clone for FieldPath<P, F>
where
    P: Clone,
{
    fn clone(&self) -> Self {
        FieldPath {
            ptr: self.ptr.clone(),
            _field: PhantomData,
        }
    }
}

impl<P, F> Copy for FieldPath<P, F> where P: Copy {}

unsafe impl<P, F> Staged for FieldPath<P, F>
where
    P: Staged,
    P::Out: StagedType,
    F: Field,
    F::Out: StagedType + 'static,
{
    // FieldPath produces a raw pointer (no lifetime)
    type Out = SPtr<F::Out>;

    fn codegen(&self, ctx: &mut CompilationContext) -> cranelift_codegen::ir::Value {
        let base_ptr = self.ptr.codegen(ctx);
        let offset = ctx.builder.ins().iconst(types::I64, F::OFFSET as i64);
        ctx.builder.ins().iadd(base_ptr, offset)
    }
}

/// Helper to create a [`FieldPath`] operation.
pub fn field_path<P, F>(ptr: P, _field: F) -> FieldPath<P, F>
where
    P: Staged,
    F: Field,
{
    FieldPath {
        ptr,
        _field: PhantomData,
    }
}

// =============================================================================
// Field Access Traits
// =============================================================================

/// `.get(field)` — load a `Copy` field's value.
///
/// Available on every struct-like receiver: by-value structs (`Var<T>`),
/// references (`Var<SRef>`/`Var<SRefMut>`), and the chained [`FieldAddr`] /
/// [`FieldPath`] results.
pub trait CopyFieldAccess<T: StagedType>: Sized + Staged {
    /// Load a `Copy` field's value.
    fn get<F>(self, field: F) -> LoadField<Self, F>
    where
        F: Field<Parent = T>,
        F::Out: CopyType,
    {
        let _ = field;
        LoadField {
            ptr: self,
            _field: PhantomData,
        }
    }
}

/// `.get_ref(field)` — a flavor-preserving reference to a field.
///
/// Only implemented for pointer/reference receivers (`S::Out: PointerLike`),
/// so you cannot take a reference into a by-value struct (which would dangle).
/// The result keeps the receiver's mutability: `&T -> &field`, `&mut T ->
/// &mut field`.
pub trait RefFieldAccess<T: StagedType>: Sized + Staged {
    /// Get a reference to a field, preserving the receiver's reference flavor.
    fn get_ref<F>(self, field: F) -> FieldAddr<Self, F>
    where
        F: Field<Parent = T>,
    {
        field_addr(self, field)
    }
}

/// `.field(field)` — navigate into a nested field of a by-value struct.
///
/// Produces a raw pointer (`SPtr`), since a by-value receiver has no lifetime
/// to borrow from. Chainable and terminable with `.get()`.
pub trait OwnedFieldAccess<T: StagedType>: Sized + Staged {
    /// Navigate to a (possibly nested) field, yielding a raw pointer.
    fn field<F>(self, field: F) -> FieldPath<Self, F>
    where
        F: Field<Parent = T>,
    {
        field_path(self, field)
    }
}

// -----------------------------------------------------------------------------
// CopyFieldAccess
// -----------------------------------------------------------------------------

// By-value struct
impl<T: StagedType> CopyFieldAccess<T> for Var<T> where Var<T>: Staged {}

// Immutable reference
impl<'a, T: StagedType> CopyFieldAccess<T> for Var<SRef<'a, T>> where Var<SRef<'a, T>>: Staged {}

// Mutable reference
impl<'a, T: StagedType> CopyFieldAccess<T> for Var<SRefMut<'a, T>> where Var<SRefMut<'a, T>>: Staged {}

// Chained Rust reference: load a field of the struct it points at. Raw
// `FieldAddr` expressions are excluded by `ReferenceLike`.
impl<S, F2> CopyFieldAccess<F2::Out> for FieldAddr<S, F2>
where
    S: Staged,
    S::Out: ReferenceLike + FieldRefOf<F2::Out>,
    F2: Field<Parent = <S::Out as PointerLike>::Pointee>,
{
}

// Chained by-value navigation.
impl<P, F2, T> CopyFieldAccess<T> for FieldPath<P, F2>
where
    P: Staged,
    P::Out: StagedType,
    F2: Field<Out = T>,
    T: StagedType,
    FieldPath<P, F2>: Staged,
{
}

// -----------------------------------------------------------------------------
// RefFieldAccess (pointer/reference receivers only)
// -----------------------------------------------------------------------------

impl<'a, T: StagedType> RefFieldAccess<T> for Var<SRef<'a, T>> where Var<SRef<'a, T>>: Staged {}

impl<'a, T: StagedType> RefFieldAccess<T> for Var<SRefMut<'a, T>> where Var<SRefMut<'a, T>>: Staged {}

// Chaining: a FieldAddr is itself a reference, so it can take a sub-field ref.
impl<S, F2> RefFieldAccess<F2::Out> for FieldAddr<S, F2>
where
    S: Staged,
    S::Out: FieldRefOf<F2::Out>,
    F2: Field<Parent = <S::Out as PointerLike>::Pointee>,
{
}

// -----------------------------------------------------------------------------
// OwnedFieldAccess (by-value receivers only)
// -----------------------------------------------------------------------------

impl<T: StagedType> OwnedFieldAccess<T> for Var<T> where Var<T>: Staged {}

impl<P, F2, T> OwnedFieldAccess<T> for FieldPath<P, F2>
where
    P: Staged,
    P::Out: StagedType,
    F2: Field<Out = T>,
    T: StagedType,
    FieldPath<P, F2>: Staged,
{
}
