//! Struct support for staged computations.
//!
//! Field access is built from just three operations, all of which compute the
//! same `base + OFFSET` address (or load from it):
//!
//! - [`LoadField`] (`.get`) — load a `Copy` field's value.
//! - [`FieldAddr`] (`.get_ref`) — a reference to a field, *flavor-preserving*
//!   via [`FieldRefOf`]: a field of a `&T` comes back as `&field`, a field of a
//!   `&mut T` comes back as `&mut field`. The mutability lives entirely in the
//!   associated [`FieldRefOf::Ref`], exactly like `SliceType::ElemRef` in
//!   [`crate::slice`].
//! - [`FieldPath`] (`.field`) — navigate into a nested field of a *by-value*
//!   struct, yielding a raw pointer (`SPtr`) because there is no input lifetime
//!   to borrow from.
//!
//! Field descriptors (the [`Field`] trait) are generated by the derive macro.

use crate::refer::{SPtr, SRef, SRefMut};
use crate::staged::{CompilationContext, Staged, Var};
use crate::types::{CopyType, StagedType};
use cranelift_codegen::ir::{types, InstBuilder, MemFlags};
use std::marker::PhantomData;

// =============================================================================
// Field Trait
// =============================================================================

/// Trait for struct field descriptors.
///
/// This trait is implemented by the proc macro for each field of a struct.
/// It provides type-level information about the field's parent struct,
/// output type, and memory offset.
pub trait Field: Copy {
    /// The parent struct type
    type Parent: StagedType;

    /// The field's type
    type Out: StagedType;

    /// Byte offset of this field from the struct base
    const OFFSET: usize;

    /// Field index (for debugging)
    const INDEX: usize;
}

// =============================================================================
// PointerLike: map a pointer-to-parent into a pointer-to-field
// =============================================================================

/// A staged pointer/reference to a parent struct, for field access.
///
/// Carries only the [`Pointee`](Self::Pointee) (the parent struct type), used
/// to constrain a [`Field`]'s `Parent`. The field-reference type itself comes
/// from [`FieldRefOf`].
pub trait PointerLike: StagedType {
    /// The type this pointer points at (the parent struct, for field access).
    type Pointee: StagedType;
}

impl<'a, P: StagedType> PointerLike for SRef<'a, P> {
    type Pointee = P;
}

impl<'a, P: StagedType> PointerLike for SRefMut<'a, P> {
    type Pointee = P;
}

/// Maps a parent pointer onto a pointer-to-field of the *same flavor*.
///
/// This is the field-access analogue of [`crate::slice::SliceType`]: a single
/// field-address op ([`FieldAddr`]) serves immutable and mutable references
/// because the result type is encoded here. A field `Out` of a `&T` becomes
/// `SRef<'a, Out>`; of a `&mut T`, `SRefMut<'a, Out>`. The `Out: 'a` bound
/// (expressible because `'a` is in scope on the impl) is what a plain GAT
/// could not state.
pub trait FieldRefOf<Out: StagedType>: PointerLike {
    /// The reference to a field of type `Out`, in this pointer's flavor.
    type Ref: StagedType;
}

impl<'a, P: StagedType, Out: StagedType + 'a> FieldRefOf<Out> for SRef<'a, P> {
    type Ref = SRef<'a, Out>;
}

impl<'a, P: StagedType, Out: StagedType + 'a> FieldRefOf<Out> for SRefMut<'a, P> {
    type Ref = SRefMut<'a, Out>;
}

// =============================================================================
// LoadField: load a Copy field's value
// =============================================================================

/// Load a field's value from a struct.
///
/// This operation is only valid for `Copy` fields. It computes the field
/// pointer (`base + OFFSET`) and loads the value from memory.
///
/// # Example
/// ```ignore
/// let pt: Var<Point> = ...;
/// let x = pt.get(PointType::x);  // Uses LoadField internally
/// ```
pub struct LoadField<P, F> {
    ptr: P,
    _field: PhantomData<F>,
}

impl<P: Clone, F> Clone for LoadField<P, F> {
    fn clone(&self) -> Self {
        Self {
            ptr: self.ptr.clone(),
            _field: PhantomData,
        }
    }
}

impl<P: Copy, F> Copy for LoadField<P, F> {}

impl<P, F> Staged for LoadField<P, F>
where
    P: Staged,
    P::Out: StagedType,
    F: Field,
    F::Out: CopyType,
{
    type Out = F::Out;

    fn codegen(&self, ctx: &mut CompilationContext) -> cranelift_codegen::ir::Value {
        let base_ptr = self.ptr.codegen(ctx);
        let offset = F::OFFSET as i32;
        ctx.builder.ins().load(
            F::Out::cranelift_type(),
            MemFlags::trusted(),
            base_ptr,
            offset,
        )
    }
}

/// Helper to create a [`LoadField`] operation.
pub fn load_field<P, F>(ptr: P, _field: F) -> LoadField<P, F>
where
    P: Staged,
    F: Field,
    F::Out: CopyType,
{
    LoadField {
        ptr,
        _field: PhantomData,
    }
}

// =============================================================================
// FieldAddr: reference to a field, flavor-preserving via PointerLike
// =============================================================================

/// A reference to a struct field, computed as `base + OFFSET`.
///
/// The reference flavor follows the parent: addressing a field of a `&T`
/// produces `SRef<'a, F>`, of a `&mut T` produces `SRefMut<'a, F>` — and the
/// input lifetime flows through, so the result can be returned. This single op
/// replaces the former `FieldRef`/`FieldMutRef`/`FieldPtr`/`FieldMutPtr`
/// quartet (they all emitted identical address arithmetic).
pub struct FieldAddr<S, F> {
    base: S,
    _field: PhantomData<F>,
}

impl<S: Clone, F> Clone for FieldAddr<S, F> {
    fn clone(&self) -> Self {
        FieldAddr {
            base: self.base.clone(),
            _field: PhantomData,
        }
    }
}

impl<S: Copy, F> Copy for FieldAddr<S, F> {}

impl<S, F> Staged for FieldAddr<S, F>
where
    S: Staged,
    S::Out: FieldRefOf<F::Out>,
    F: Field<Parent = <S::Out as PointerLike>::Pointee>,
{
    type Out = <S::Out as FieldRefOf<F::Out>>::Ref;

    fn codegen(&self, ctx: &mut CompilationContext) -> cranelift_codegen::ir::Value {
        let base_ptr = self.base.codegen(ctx);
        let offset = ctx.builder.ins().iconst(types::I64, F::OFFSET as i64);
        ctx.builder.ins().iadd(base_ptr, offset)
    }
}

/// Helper to create a [`FieldAddr`] operation.
pub fn field_addr<S, F>(base: S, _field: F) -> FieldAddr<S, F> {
    FieldAddr {
        base,
        _field: PhantomData,
    }
}

// =============================================================================
// FieldPath: lifetime-free navigation for by-value structs
// =============================================================================

/// Lifetime-free field path for accessing nested fields of by-value structs.
///
/// Used when the receiver is passed by value (`Var<T>`): there is no input
/// lifetime to borrow, so navigation yields a raw pointer (`SPtr<F::Out>`).
/// `FieldPath` can be chained further with `.field()` or terminated with
/// `.get()` for `Copy` values.
///
/// # Example
/// ```ignore
/// compiler.fun1("sum", |_ctx, outer: Var<Outer>| {
///     outer.field(OuterType::inner).get(InnerType::value)
/// });
/// ```
pub struct FieldPath<P, F> {
    ptr: P,
    _field: PhantomData<F>,
}

impl<P, F> Clone for FieldPath<P, F>
where
    P: Clone,
{
    fn clone(&self) -> Self {
        FieldPath {
            ptr: self.ptr.clone(),
            _field: PhantomData,
        }
    }
}

impl<P, F> Copy for FieldPath<P, F> where P: Copy {}

impl<P, F> Staged for FieldPath<P, F>
where
    P: Staged,
    P::Out: StagedType,
    F: Field,
    F::Out: StagedType + 'static,
{
    // FieldPath produces a raw pointer (no lifetime)
    type Out = SPtr<F::Out>;

    fn codegen(&self, ctx: &mut CompilationContext) -> cranelift_codegen::ir::Value {
        let base_ptr = self.ptr.codegen(ctx);
        let offset = ctx.builder.ins().iconst(types::I64, F::OFFSET as i64);
        ctx.builder.ins().iadd(base_ptr, offset)
    }
}

/// Helper to create a [`FieldPath`] operation.
pub fn field_path<P, F>(ptr: P, _field: F) -> FieldPath<P, F>
where
    P: Staged,
    F: Field,
{
    FieldPath {
        ptr,
        _field: PhantomData,
    }
}

// =============================================================================
// Field Access Traits
// =============================================================================

/// `.get(field)` — load a `Copy` field's value.
///
/// Available on every struct-like receiver: by-value structs (`Var<T>`),
/// references (`Var<SRef>`/`Var<SRefMut>`), and the chained [`FieldAddr`] /
/// [`FieldPath`] results.
pub trait CopyFieldAccess<T: StagedType>: Sized + Staged {
    /// Load a `Copy` field's value.
    fn get<F>(self, field: F) -> LoadField<Self, F>
    where
        F: Field<Parent = T>,
        F::Out: CopyType,
    {
        load_field(self, field)
    }
}

/// `.get_ref(field)` — a flavor-preserving reference to a field.
///
/// Only implemented for pointer/reference receivers (`S::Out: PointerLike`),
/// so you cannot take a reference into a by-value struct (which would dangle).
/// The result keeps the receiver's mutability: `&T -> &field`, `&mut T ->
/// &mut field`.
pub trait RefFieldAccess<T: StagedType>: Sized + Staged {
    /// Get a reference to a field, preserving the receiver's reference flavor.
    fn get_ref<F>(self, field: F) -> FieldAddr<Self, F>
    where
        F: Field<Parent = T>,
    {
        field_addr(self, field)
    }
}

/// `.field(field)` — navigate into a nested field of a by-value struct.
///
/// Produces a raw pointer (`SPtr`), since a by-value receiver has no lifetime
/// to borrow from. Chainable and terminable with `.get()`.
pub trait OwnedFieldAccess<T: StagedType>: Sized + Staged {
    /// Navigate to a (possibly nested) field, yielding a raw pointer.
    fn field<F>(self, field: F) -> FieldPath<Self, F>
    where
        F: Field<Parent = T>,
    {
        field_path(self, field)
    }
}

// -----------------------------------------------------------------------------
// CopyFieldAccess
// -----------------------------------------------------------------------------

// By-value struct
impl<T: StagedType> CopyFieldAccess<T> for Var<T> where Var<T>: Staged {}

// Immutable reference
impl<'a, T: StagedType> CopyFieldAccess<T> for Var<SRef<'a, T>> where Var<SRef<'a, T>>: Staged {}

// Mutable reference
impl<'a, T: StagedType> CopyFieldAccess<T> for Var<SRefMut<'a, T>> where Var<SRefMut<'a, T>>: Staged {}

// Chained reference: load a field of the struct a FieldAddr points at.
impl<S, F2> CopyFieldAccess<F2::Out> for FieldAddr<S, F2>
where
    S: Staged,
    S::Out: FieldRefOf<F2::Out>,
    F2: Field<Parent = <S::Out as PointerLike>::Pointee>,
{
}

// Chained by-value navigation.
impl<P, F2, T> CopyFieldAccess<T> for FieldPath<P, F2>
where
    P: Staged,
    P::Out: StagedType,
    F2: Field<Out = T>,
    T: StagedType,
    FieldPath<P, F2>: Staged,
{
}

// -----------------------------------------------------------------------------
// RefFieldAccess (pointer/reference receivers only)
// -----------------------------------------------------------------------------

impl<'a, T: StagedType> RefFieldAccess<T> for Var<SRef<'a, T>> where Var<SRef<'a, T>>: Staged {}

impl<'a, T: StagedType> RefFieldAccess<T> for Var<SRefMut<'a, T>> where Var<SRefMut<'a, T>>: Staged {}

// Chaining: a FieldAddr is itself a reference, so it can take a sub-field ref.
impl<S, F2> RefFieldAccess<F2::Out> for FieldAddr<S, F2>
where
    S: Staged,
    S::Out: FieldRefOf<F2::Out>,
    F2: Field<Parent = <S::Out as PointerLike>::Pointee>,
{
}

// -----------------------------------------------------------------------------
// OwnedFieldAccess (by-value receivers only)
// -----------------------------------------------------------------------------

impl<T: StagedType> OwnedFieldAccess<T> for Var<T> where Var<T>: Staged {}

impl<P, F2, T> OwnedFieldAccess<T> for FieldPath<P, F2>
where
    P: Staged,
    P::Out: StagedType,
    F2: Field<Out = T>,
    T: StagedType,
    FieldPath<P, F2>: Staged,
{
}
