[workspace]
members = ["rust-lms", "rust-lms-derive", "arrow-lms", "sql-gen"]
resolver = "2"

[workspace.dependencies]
rust-lms = { path = "rust-lms" }
rust-lms-derive = { path = "rust-lms-derive" }
# Parsing
nom = "7.1"

# Error handling & diagnostics
thiserror = "1.0"
ariadne = "0.4"

# JIT compilation
cranelift = "0.127.1"
cranelift-jit = "0.127.1"
cranelift-module = "0.127.1"
cranelift-frontend = "0.127.1"
cranelift-codegen = "0.127.1"
cranelift-native = "0.127.1"

arrow = "57.2.0"
datafusion-sql = "52.0.0"

# Graph algorithms for SSA
petgraph = "0.6"

# Performance utilities
ahash = "0.8"

# Testing
either = "=1.15.0"
proptest = "1.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
