[workspace]
members = ["rust-lms", "rust-lms-derive", "rust-lms-std", "arrow-lms", "sql-gen"]
resolver = "2"

[workspace.dependencies]
rust-lms = { path = "rust-lms" }
rust-lms-derive = { path = "rust-lms-derive" }
rust-lms-std = { path = "rust-lms-std" }
arrow-lms = { path = "arrow-lms" }
# Parsing
nom = "7.1"

# Error handling & diagnostics
thiserror = "1.0"
ariadne = "0.4"

# JIT compilation
cranelift = "0.134"
cranelift-jit = "0.134"
cranelift-module = "0.134"
cranelift-frontend = "0.134"
cranelift-codegen = "0.134"
cranelift-native = "0.134"

arrow = "58.3.0"
datafusion-sql = "54.1.0"

# Performance utilities
ahash = "0.8"
hashbrown = "0.17"

# Testing
either = "=1.18.0"
proptest = "1.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
criterion = { version = "0.8.2", features = ["html_reports"] }
rand = "0.9"

# sql
datafusion-common = "54.1.0"
datafusion-expr = "54.1.0"
datafusion-functions = "54.1.0"
datafusion-functions-aggregate = "54.1.0"
datafusion-optimizer = "54.1.0"
