//! Derive macros for JIT compilation support.
//!
//! This crate provides:
//! - `StagedType`: Generate `StructDef` from `#[repr(C)]` structs
//! - `extern_fn`: Auto-derive types for external functions
//!
//! # Example
//!
//! ```ignore
//! use tutorial_derive::StagedType;
//!
//! #[derive(StagedType)]
//! #[repr(C)]
//! struct Edge {
//!     src: u64,
//!     dst: u64,
//! }
//!
//! // This generates:
//! // impl Edge {
//! //     pub fn struct_def() -> Arc<StructDef> { ... }
//! // }
//! ```

use proc_macro::TokenStream;
use quote::quote;
use syn::{parse_macro_input, Data, DeriveInput, Fields, FnArg, ItemFn, ReturnType, Type};

/// Derive macro that generates a `struct_def()` method returning `Arc<StructDef>`.
///
/// The struct must be `#[repr(C)]` to ensure predictable memory layout.
/// All fields must be supported primitive types or nested `#[repr(C)]` structs.
///
/// # Supported field types
///
/// - `u8`, `i8` -> `DataType::U8`, `DataType::I8`
/// - `u16`, `i16` -> `DataType::U16`, `DataType::I16`
/// - `u32`, `i32` -> `DataType::U32`, `DataType::I32`
/// - `u64`, `i64` -> `DataType::U64`, `DataType::I64`
/// - `f32`, `f64` -> `DataType::F32`, `DataType::F64`
/// - `bool` -> `DataType::Bool`
/// - Other types that implement `StagedType` -> nested struct
#[proc_macro_derive(StagedType)]
pub fn derive_staged_type(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);

    let name = &input.ident;
    let name_str = name.to_string();

    // Check for repr(C)
    let has_repr_c = input.attrs.iter().any(|attr| {
        if attr.path().is_ident("repr") {
            if let Ok(nested) = attr.parse_args::<syn::Ident>() {
                return nested == "C";
            }
        }
        false
    });

    if !has_repr_c {
        return syn::Error::new_spanned(
            &input,
            "StagedType can only be derived for #[repr(C)] structs",
        )
        .to_compile_error()
        .into();
    }

    // Extract fields
    let fields = match &input.data {
        Data::Struct(data) => match &data.fields {
            Fields::Named(fields) => &fields.named,
            _ => {
                return syn::Error::new_spanned(
                    &input,
                    "StagedType can only be derived for structs with named fields",
                )
                .to_compile_error()
                .into();
            }
        },
        _ => {
            return syn::Error::new_spanned(&input, "StagedType can only be derived for structs")
                .to_compile_error()
                .into();
        }
    };

    // Generate field additions for the builder
    let field_additions: Vec<_> = fields
        .iter()
        .map(|field| {
            let field_name = field.ident.as_ref().unwrap();
            let field_name_str = field_name.to_string();
            let field_type = &field.ty;

            let data_type_expr = type_to_datatype(field_type);

            quote! {
                .field(#field_name_str, #data_type_expr)
            }
        })
        .collect();

    // Generate the impl
    let expanded = quote! {
        impl #name {
            /// Get the `StructDef` that describes this struct's memory layout.
            ///
            /// This is automatically generated by the `StagedType` derive macro
            /// and matches the `#[repr(C)]` layout of this struct.
            pub fn struct_def() -> ::std::sync::Arc<crate::struct_type::StructDef> {
                ::std::sync::Arc::new(
                    crate::struct_type::StructDef::builder(#name_str)
                        #(#field_additions)*
                        .build()
                )
            }
        }
    };

    TokenStream::from(expanded)
}

/// Convert a Rust type to the corresponding DataType expression
fn type_to_datatype(ty: &Type) -> proc_macro2::TokenStream {
    type_to_datatype_impl(ty, false)
}

/// Convert a Rust type to DataType with context (for parameters vs return types)
fn type_to_datatype_impl(ty: &Type, _is_param: bool) -> proc_macro2::TokenStream {
    match ty {
        Type::Path(type_path) => {
            let path = &type_path.path;

            // Check for slice types &[T]
            if let Some(segment) = path.segments.first() {
                if segment.ident == "Option" || segment.ident == "Vec" {
                    return quote! {
                        compile_error!("Option and Vec types not supported in extern functions. Use raw pointers instead.")
                    };
                }
            }

            if path.is_ident("u8") {
                quote! { crate::DataType::U8 }
            } else if path.is_ident("i8") {
                quote! { crate::DataType::I8 }
            } else if path.is_ident("u16") {
                quote! { crate::DataType::U16 }
            } else if path.is_ident("i16") {
                quote! { crate::DataType::I16 }
            } else if path.is_ident("u32") {
                quote! { crate::DataType::U32 }
            } else if path.is_ident("i32") {
                quote! { crate::DataType::I32 }
            } else if path.is_ident("u64") {
                quote! { crate::DataType::U64 }
            } else if path.is_ident("i64") {
                quote! { crate::DataType::I64 }
            } else if path.is_ident("f32") {
                quote! { crate::DataType::F32 }
            } else if path.is_ident("f64") {
                quote! { crate::DataType::F64 }
            } else if path.is_ident("bool") {
                quote! { crate::DataType::Bool }
            } else if path.is_ident("usize") {
                // usize maps to u64 on 64-bit platforms
                quote! { crate::DataType::U64 }
            } else if path.is_ident("isize") {
                // isize maps to i64 on 64-bit platforms
                quote! { crate::DataType::I64 }
            } else {
                // Assume it's a nested struct that also derives StagedType
                // At compile time, we verify it has struct_def() method
                let type_name = path.segments.last().unwrap().ident.clone();
                quote! {
                    {
                        // This will cause a compile error if #type_name doesn't implement StagedType
                        let _ = #type_name::struct_def;
                        crate::DataType::Struct(#type_name::struct_def())
                    }
                }
            }
        }
        Type::Reference(type_ref) => {
            // Handle &T and &mut T
            let elem_ty = &*type_ref.elem;

            // Check for slice &[T] or &mut [T]
            if let Type::Slice(slice_ty) = elem_ty {
                let elem_type = type_to_datatype_impl(&*slice_ty.elem, false);
                if type_ref.mutability.is_some() {
                    // &mut [T] -> mut_arr(T)
                    quote! { crate::DataType::mut_arr(#elem_type) }
                } else {
                    // &[T] -> arr(T)
                    quote! { crate::DataType::arr(#elem_type) }
                }
            } else {
                // &T or &mut T -> ExtPtr
                // For FFI, references to structs become ExtPtr
                let type_name = quote! { #elem_ty }.to_string();
                quote! { crate::DataType::ExtPtr(#type_name.to_string()) }
            }
        }
        Type::Ptr(type_ptr) => {
            // Handle *const T and *mut T -> ExtPtr
            let elem_ty = &*type_ptr.elem;
            let type_name = quote! { #elem_ty }.to_string();
            quote! { crate::DataType::ExtPtr(#type_name.to_string()) }
        }
        _ => {
            // Fallback: generate a compile error
            quote! {
                compile_error!("Unsupported type for JIT compilation. Supported types: primitives (i64, u64, etc.), &[T], &mut [T], *const T, *mut T, and #[repr(C)] structs with StagedType")
            }
        }
    }
}

/// Attribute macro for extern "C" functions that auto-generates type metadata.
///
/// This macro:
/// 1. Extracts parameter and return types
/// 2. Validates that struct types implement `StagedType`
/// 3. Generates a const containing the function signature metadata
///
/// # Example
///
/// ```ignore
/// #[extern_fn]
/// pub extern "C" fn my_add(x: i64, y: i64) -> i64 {
///     x + y
/// }
///
/// // Generates:
/// // pub const MY_ADD_SIGNATURE: ExternFnSignature = ExternFnSignature {
/// //     name: "my_add",
/// //     param_types: &[DataType::I64, DataType::I64],
/// //     return_type: DataType::I64,
/// //     fn_ptr: my_add as *const u8,
/// // };
/// ```
#[proc_macro_attribute]
pub fn extern_fn(_attr: TokenStream, item: TokenStream) -> TokenStream {
    let input = parse_macro_input!(item as ItemFn);

    // Verify it's extern "C"
    let is_extern_c = input.sig.abi.as_ref()
        .and_then(|abi| abi.name.as_ref())
        .map(|name| name.value() == "C")
        .unwrap_or(false);

    if !is_extern_c {
        return syn::Error::new_spanned(
            &input.sig.abi,
            "#[extern_fn] can only be used on extern \"C\" functions"
        )
        .to_compile_error()
        .into();
    }

    let fn_name = &input.sig.ident;

    // Extract parameter types
    let mut param_types = Vec::new();
    for input_arg in &input.sig.inputs {
        match input_arg {
            FnArg::Typed(pat_type) => {
                let ty = &*pat_type.ty;
                param_types.push(type_to_datatype_impl(ty, true));
            }
            FnArg::Receiver(_) => {
                return syn::Error::new_spanned(
                    input_arg,
                    "extern \"C\" functions cannot have self parameters"
                )
                .to_compile_error()
                .into();
            }
        }
    }

    // Extract return type
    let return_type = match &input.sig.output {
        ReturnType::Default => quote! { crate::DataType::Unit },
        ReturnType::Type(_, ty) => type_to_datatype_impl(ty, false),
    };

    let fn_name_str = fn_name.to_string();
    let signature_fn_name = syn::Ident::new(&format!("{}_signature", fn_name), fn_name.span());

    // Generate the output
    let expanded = quote! {
        #input

        /// Auto-generated signature metadata for this extern function
        #[allow(non_snake_case)]
        pub fn #signature_fn_name() -> crate::ffi::ExternFnSignature {
            crate::ffi::ExternFnSignature {
                name: #fn_name_str,
                param_types: Box::leak(Box::new([#(#param_types),*])),
                return_type: #return_type,
                fn_ptr: #fn_name as *const u8,
            }
        }
    };

    TokenStream::from(expanded)
}
