//! Derive macro for generating `StructDef` from `#[repr(C)]` structs.
//!
//! This crate provides the `StagedType` derive macro which automatically generates
//! a `StructDef` that matches the memory layout of a `#[repr(C)]` struct.
//!
//! # Example
//!
//! ```ignore
//! use tutorial_derive::StagedType;
//!
//! #[derive(StagedType)]
//! #[repr(C)]
//! struct Edge {
//!     src: u64,
//!     dst: u64,
//! }
//!
//! // This generates:
//! // impl Edge {
//! //     pub fn struct_def() -> Arc<StructDef> { ... }
//! // }
//! ```

use proc_macro::TokenStream;
use quote::quote;
use syn::{parse_macro_input, Data, DeriveInput, Fields, Type};

/// Derive macro that generates a `struct_def()` method returning `Arc<StructDef>`.
///
/// The struct must be `#[repr(C)]` to ensure predictable memory layout.
/// All fields must be supported primitive types or nested `#[repr(C)]` structs.
///
/// # Supported field types
///
/// - `u8`, `i8` -> `DataType::U8`, `DataType::I8`
/// - `u16`, `i16` -> `DataType::U16`, `DataType::I16`
/// - `u32`, `i32` -> `DataType::U32`, `DataType::I32`
/// - `u64`, `i64` -> `DataType::U64`, `DataType::I64`
/// - `f32`, `f64` -> `DataType::F32`, `DataType::F64`
/// - `bool` -> `DataType::Bool`
/// - Other types that implement `StagedType` -> nested struct
#[proc_macro_derive(StagedType)]
pub fn derive_staged_type(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);

    let name = &input.ident;
    let name_str = name.to_string();

    // Check for repr(C)
    let has_repr_c = input.attrs.iter().any(|attr| {
        if attr.path().is_ident("repr") {
            if let Ok(nested) = attr.parse_args::<syn::Ident>() {
                return nested == "C";
            }
        }
        false
    });

    if !has_repr_c {
        return syn::Error::new_spanned(
            &input,
            "StagedType can only be derived for #[repr(C)] structs",
        )
        .to_compile_error()
        .into();
    }

    // Extract fields
    let fields = match &input.data {
        Data::Struct(data) => match &data.fields {
            Fields::Named(fields) => &fields.named,
            _ => {
                return syn::Error::new_spanned(
                    &input,
                    "StagedType can only be derived for structs with named fields",
                )
                .to_compile_error()
                .into();
            }
        },
        _ => {
            return syn::Error::new_spanned(&input, "StagedType can only be derived for structs")
                .to_compile_error()
                .into();
        }
    };

    // Generate field additions for the builder
    let field_additions: Vec<_> = fields
        .iter()
        .map(|field| {
            let field_name = field.ident.as_ref().unwrap();
            let field_name_str = field_name.to_string();
            let field_type = &field.ty;

            let data_type_expr = type_to_datatype(field_type);

            quote! {
                .field(#field_name_str, #data_type_expr)
            }
        })
        .collect();

    // Generate the impl
    let expanded = quote! {
        impl #name {
            /// Get the `StructDef` that describes this struct's memory layout.
            ///
            /// This is automatically generated by the `StagedType` derive macro
            /// and matches the `#[repr(C)]` layout of this struct.
            pub fn struct_def() -> ::std::sync::Arc<crate::struct_type::StructDef> {
                ::std::sync::Arc::new(
                    crate::struct_type::StructDef::builder(#name_str)
                        #(#field_additions)*
                        .build()
                )
            }
        }
    };

    TokenStream::from(expanded)
}

/// Convert a Rust type to the corresponding DataType expression
fn type_to_datatype(ty: &Type) -> proc_macro2::TokenStream {
    match ty {
        Type::Path(type_path) => {
            let path = &type_path.path;
            if path.is_ident("u8") {
                quote! { crate::DataType::U8 }
            } else if path.is_ident("i8") {
                quote! { crate::DataType::I8 }
            } else if path.is_ident("u16") {
                quote! { crate::DataType::U16 }
            } else if path.is_ident("i16") {
                quote! { crate::DataType::I16 }
            } else if path.is_ident("u32") {
                quote! { crate::DataType::U32 }
            } else if path.is_ident("i32") {
                quote! { crate::DataType::I32 }
            } else if path.is_ident("u64") {
                quote! { crate::DataType::U64 }
            } else if path.is_ident("i64") {
                quote! { crate::DataType::I64 }
            } else if path.is_ident("f32") {
                quote! { crate::DataType::F32 }
            } else if path.is_ident("f64") {
                quote! { crate::DataType::F64 }
            } else if path.is_ident("bool") {
                quote! { crate::DataType::Bool }
            } else if path.is_ident("usize") {
                // usize maps to u64 on 64-bit platforms
                quote! { crate::DataType::U64 }
            } else if path.is_ident("isize") {
                // isize maps to i64 on 64-bit platforms
                quote! { crate::DataType::I64 }
            } else {
                // Assume it's a nested struct that also derives StagedType
                let type_name = path.segments.last().unwrap().ident.clone();
                quote! {
                    crate::DataType::Struct(#type_name::struct_def())
                }
            }
        }
        _ => {
            // Fallback: generate a compile error
            quote! {
                compile_error!("Unsupported field type for StagedType")
            }
        }
    }
}
