[package]
name = "sql-gen"
version = "0.1.0"
edition = "2024"

[dependencies]
datafusion-sql.workspace = true
arrow.workspace = true
rust-lms.workspace = true
arrow-lms.workspace = true
datafusion-common.workspace = true
datafusion-expr.workspace = true
datafusion-functions.workspace = true
datafusion-functions-aggregate.workspace = true
