use crate::error::DioError;
use crate::ssa::{SsaInstruction, SsaProgram, SsaValue};
use cranelift::prelude::*;
use cranelift_frontend::{FunctionBuilder, FunctionBuilderContext};
use cranelift_jit::{JITBuilder, JITModule};
use cranelift_module::{default_libcall_names, Linkage, Module};
use std::collections::HashMap;
use std::env;

/// Cranelift backend for compiling SSA IR to machine code
pub struct CraneliftBackend {
    builder_context: FunctionBuilderContext,
    context: codegen::Context,
    module: JITModule,
}

impl CraneliftBackend {
    pub fn new() -> Result<Self, DioError> {
        let builder = JITBuilder::with_isa(
            cranelift_native::builder()
                .map_err(|e| DioError::Compilation(format!("Failed to create ISA builder: {e}")))?
                .finish(settings::Flags::new(settings::builder()))
                .map_err(|e| DioError::Compilation(format!("Failed to create ISA: {e}")))?,
            default_libcall_names(),
        );

        let module = JITModule::new(builder);

        Ok(Self {
            builder_context: FunctionBuilderContext::new(),
            context: module.make_context(),
            module,
        })
    }

    /// Compile SSA program to an executable function
    pub fn compile(&mut self, program: &SsaProgram) -> Result<*const u8, DioError> {
        // Define the function signature
        // For now, we assume a binary operation signature:
        // fn(a_ptr: *const u8, b_ptr: *const u8, length: u64, output_ptr: *mut u8)
        self.context.func.signature.params.push(AbiParam::new(types::I64)); // a_ptr
        self.context.func.signature.params.push(AbiParam::new(types::I64)); // b_ptr
        self.context.func.signature.params.push(AbiParam::new(types::I64)); // length
        self.context.func.signature.params.push(AbiParam::new(types::I64)); // output_ptr

        let mut builder = FunctionBuilder::new(&mut self.context.func, &mut self.builder_context);
        let mut ssa_to_cranelift = HashMap::<SsaValue, Value>::new();

        // Create the entry block
        let entry_block = builder.create_block();
        builder.switch_to_block(entry_block);
        builder.append_block_params_for_function_params(entry_block);

        // Create main loop structure
        let loop_header = builder.create_block();
        let loop_body = builder.create_block();
        let loop_exit = builder.create_block();
        builder.append_block_param(loop_header, types::I64); // loop variable `i`

        let length = builder.block_params(entry_block)[2];
        let zero = builder.ins().iconst(types::I64, 0);
        builder.ins().jump(loop_header, &[zero]);

        // --- Loop Header ---
        builder.switch_to_block(loop_header);
        let i = builder.block_params(loop_header)[0];
        let condition = builder.ins().icmp(IntCC::UnsignedLessThan, i, length);
        builder.ins().brif(condition, loop_body, &[], loop_exit, &[]);

        // --- Loop Body ---
        builder.switch_to_block(loop_body);

        // This is a simplified interpreter that only works for the specific SSA
        // programs generated by `convert_simple_addition` and `convert_simple_subtraction`.
        let body_block = program
            .blocks
            .values()
            .find(|b| !b.instructions.is_empty() && matches!(b.instructions[0], SsaInstruction::ArrayAccess{..}));

        if let Some(body_block) = body_block {
            for instruction in &body_block.instructions {
                match instruction {
                    SsaInstruction::ArrayAccess { dest, array, index: _ } => {
                        // Determine if this is array 'a' or 'b' based on a simple heuristic
                        // (This is brittle and should be improved with better SSA)
                        let param_index = if ssa_to_cranelift.is_empty() { 0 } else { 1 };
                        let array_ptr = builder.block_params(entry_block)[param_index];
                        
                        let eight = builder.ins().iconst(types::I64, 8);
                        let offset = builder.ins().imul(i, eight);
                        let addr = builder.ins().iadd(array_ptr, offset);
                        let val = builder.ins().load(types::I64, MemFlags::trusted(), addr, 0);
                        ssa_to_cranelift.insert(*dest, val);
                    }
                    SsaInstruction::Add { dest, lhs, rhs } => {
                        let lhs_val = ssa_to_cranelift[lhs];
                        let rhs_val = ssa_to_cranelift[rhs];
                        let result = builder.ins().iadd(lhs_val, rhs_val);
                        ssa_to_cranelift.insert(*dest, result);
                    }
                    SsaInstruction::Sub { dest, lhs, rhs } => {
                        let lhs_val = ssa_to_cranelift[lhs];
                        let rhs_val = ssa_to_cranelift[rhs];
                        let result = builder.ins().isub(lhs_val, rhs_val);
                        ssa_to_cranelift.insert(*dest, result);
                    }
                    SsaInstruction::StoreArrayElement { array: _, index: _, value } => {
                        let output_ptr = builder.block_params(entry_block)[3];
                        let result_val = ssa_to_cranelift[value];
                        
                        let eight = builder.ins().iconst(types::I64, 8);
                        let offset = builder.ins().imul(i, eight);
                        let addr = builder.ins().iadd(output_ptr, offset);
                        builder.ins().store(MemFlags::trusted(), result_val, addr, 0);
                    }
                    _ => {} // Ignore other instructions for now
                }
            }
        }

        // Increment loop counter and jump back to header
        let one = builder.ins().iconst(types::I64, 1);
        let next_i = builder.ins().iadd(i, one);
        builder.ins().jump(loop_header, &[next_i]);

        // --- Loop Exit ---
        builder.switch_to_block(loop_exit);
        builder.ins().return_(&[]);

        builder.seal_all_blocks();
        builder.finalize();

        // Print the function for debugging if requested
        if env::var("DIO_DEBUG_JIT").is_ok() {
            println!("--- Cranelift IR ---");
            println!("{}", self.context.func.display());
            println!("--------------------");
        }

        // Declare and define the function
        let func_id = self
            .module
            .declare_function("dio_jitted_func", Linkage::Export, &self.context.func.signature)
            .map_err(|e| DioError::Compilation(format!("Failed to declare function: {e}")))?;

        self.module
            .define_function(func_id, &mut self.context)
            .map_err(|e| DioError::Compilation(format!("Failed to define function: {e}")))?;

        self.module.clear_context(&mut self.context);
        self.module.finalize_definitions().map_err(|e| {
            DioError::Compilation(format!("Failed to finalize definitions: {e}"))
        })?;

        Ok(self.module.get_finalized_function(func_id))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{parse_expr, ssa::ast_to_ssa};

    #[test]
    fn test_cranelift_compilation_add() {
        let expr = parse_expr("(lambda ([I64Array a] [I64Array b] I64Array) (+ a b))").unwrap();
        let ssa_program = ast_to_ssa(&expr).unwrap();

        let mut backend = CraneliftBackend::new().unwrap();
        let _compiled_fn = backend.compile(&ssa_program);
        // If we get here without panicking, compilation succeeded
    }

    #[test]
    fn test_cranelift_compilation_sub() {
        let expr = parse_expr("(lambda ([I64Array a] [I64Array b] I64Array) (- a b))").unwrap();
        let ssa_program = ast_to_ssa(&expr).unwrap();

        let mut backend = CraneliftBackend::new().unwrap();
        let _compiled_fn = backend.compile(&ssa_program);
        // If we get here without panicking, compilation succeeded
    }
}
